In [ ]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

# Display wider tables
pd.set_option("display.width", 1000)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [ ]:
df = pd.read_csv("/content/healthcare_dataset.csv")
df.head()

            Name  Age  Gender Blood Type Medical Condition Date of Admission            Doctor                    Hospital Insurance Provider  Billing Amount  Room Number Admission Type Discharge Date   Medication  Test Results
0  Bobby JacksOn   30    Male         B-            Cancer        2024-01-31     Matthew Smith             Sons and Miller         Blue Cross    18856.281306          328         Urgent     2024-02-02  Paracetamol        Normal
1   LesLie TErRy   62    Male         A+           Obesity        2019-08-20   Samantha Davies                     Kim Inc           Medicare    33643.327287          265      Emergency     2019-08-26    Ibuprofen  Inconclusive
2    DaNnY sMitH   76  Female         A-           Obesity        2022-09-22  Tiffany Mitchell                    Cook PLC              Aetna    27955.096079          205      Emergency     2022-10-07      Aspirin        Normal
3   andrEw waTtS   28  Female         O+          Diabetes        2020-11-18       Kevin Wells  Hernandez Rogers and Vang,           Medicare    37909.782410          450       Elective     2020-12-18    Ibuprofen      Abnormal
4  adrIENNE bEll   43  Female        AB+            Cancer        2022-09-19    Kathleen Hanna                 White-White              Aetna    14238.317814          458         Urgent     2022-10-09   Penicillin      Abnormal

In [ ]:
df.tail()

                    Name  Age  Gender Blood Type Medical Condition Date of Admission           Doctor                      Hospital Insurance Provider  Billing Amount  Room Number Admission Type Discharge Date  Medication Test Results
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma        2020-08-16    Joshua Jarvis                Jones-Thompson         Blue Cross     2650.714952          417       Elective     2020-09-15  Penicillin     Abnormal
55496         KYle pEREz   61  Female        AB-           Obesity        2020-01-23  Taylor Sullivan                  Tucker-Moyer              Cigna    31457.797307          316       Elective     2020-02-01     Aspirin       Normal
55497       HEATher WaNG   38  Female         B+      Hypertension        2020-07-13   Joe Jacobs DVM  and Mahoney Johnson Vasquez,   UnitedHealthcare    27620.764717          347         Urgent     2020-08-10   Ibuprofen     Abnormal
55498     JENniFER JOneS   43    Male         O-         Arthritis        2019-05-25   Kimberly Curry      Jackson Todd and Castro,           Medicare    32451.092358          321       Elective     2019-05-31   Ibuprofen     Abnormal
55499       jAMES GARCiA   53  Female         O+         Arthritis        2024-04-02    Dennis Warren                Henry Sons and              Aetna     4010.134172          448         Urgent     2024-04-29   Ibuprofen     Abnormal

In [ ]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 55500
Columns : 15

In [ ]:
print(df.columns)

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date', 'Medication', 'Test Results'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [ ]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [ ]:
#  Categorical Columns
df.describe(include="object")

               Name Gender Blood Type Medical Condition Date of Admission         Doctor   Hospital Insurance Provider Admission Type Discharge Date Medication Test Results
count         55500  55500      55500             55500             55500          55500      55500              55500          55500          55500      55500        55500
unique        49992      2          8                 6              1827          40341      39876                  5              3           1856          5            3
top     DAvId muNoZ   Male         A-         Arthritis        2024-03-16  Michael Smith  LLC Smith              Cigna       Elective     2020-03-15    Lipitor     Abnormal
freq              3  27774       6969              9308                50             27         44              11249          18655             53      11140        18627

In [ ]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean()*100,2)
})

missing

                    Missing Values  Percentage
Name                             0         0.0
Age                              0         0.0
Gender                           0         0.0
Blood Type                       0         0.0
Medical Condition                0         0.0
Date of Admission                0         0.0
Doctor                           0         0.0
Hospital                         0         0.0
Insurance Provider               0         0.0
Billing Amount                   0         0.0
Room Number                      0         0.0
Admission Type                   0         0.0
Discharge Date                   0         0.0
Medication                       0         0.0
Test Results                     0         0.0

In [ ]:
df.duplicated().sum()

np.int64(534)

In [ ]:
duplicates = df[df.duplicated()]

duplicates.head()

                     Name  Age  Gender Blood Type Medical Condition Date of Admission             Doctor        Hospital Insurance Provider  Billing Amount  Room Number Admission Type Discharge Date  Medication  Test Results
50023        Samuel joYCe   56    Male         O+         Arthritis        2022-11-03     Krista Hartman  Thomas-Ballard   UnitedHealthcare    15654.830587          157         Urgent     2022-11-22     Aspirin  Inconclusive
50040    KIMBErly vasqueZ   26    Male         A-           Obesity        2023-10-23   Jennifer Bennett       Cowan Inc   UnitedHealthcare    38142.109678          313         Urgent     2023-11-18  Penicillin      Abnormal
50055      SCoTT tHOrNton   55  Female         B-           Obesity        2021-04-08      Joshua Ingram      Keller LLC           Medicare    30894.904511          455         Urgent     2021-04-15     Aspirin      Abnormal
50070         wiLliam LEe   27  Female         O+         Arthritis        2020-01-31  Lauren Montgomery   Winters-Simon              Cigna    46229.434901          153       Elective     2020-02-13     Lipitor        Normal
50078  chRistOPheR NoRrIs   38    Male        AB-         Arthritis        2023-01-14       Denise Blair     Inc Morales           Medicare     9072.127142          452      Emergency     2023-02-12  Penicillin        Normal

In [ ]:
df = df.drop_duplicates().reset_index(drop=True)

print("New Shape:", df.shape)

New Shape: (54966, 15)

In [ ]:
print("Duplicate Records:", df.duplicated().sum())

Duplicate Records: 0

In [ ]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

df.columns

Index(['name', 'age', 'gender', 'blood_type', 'medical_condition', 'date_of_admission', 'doctor', 'hospital', 'insurance_provider', 'billing_amount', 'room_number', 'admission_type', 'discharge_date', 'medication', 'test_results'], dtype='object')

In [ ]:
df["date_of_admission"] = pd.to_datetime(df["date_of_admission"])

df["discharge_date"] = pd.to_datetime(df["discharge_date"])

In [ ]:
# Create Age Groups
bins = [0,18,35,50,65,100]

labels = [
    "Child",
    "Young Adult",
    "Adult",
    "Senior",
    "Elderly"
]

df["age_group"] = pd.cut(
    df["age"],
    bins=bins,
    labels=labels
)
df.head()

            name  age  gender blood_type medical_condition date_of_admission            doctor                    hospital insurance_provider  billing_amount  room_number admission_type discharge_date   medication  test_results    age_group
0  Bobby JacksOn   30    Male         B-            Cancer        2024-01-31     Matthew Smith             Sons and Miller         Blue Cross    18856.281306          328         Urgent     2024-02-02  Paracetamol        Normal  Young Adult
1   LesLie TErRy   62    Male         A+           Obesity        2019-08-20   Samantha Davies                     Kim Inc           Medicare    33643.327287          265      Emergency     2019-08-26    Ibuprofen  Inconclusive       Senior
2    DaNnY sMitH   76  Female         A-           Obesity        2022-09-22  Tiffany Mitchell                    Cook PLC              Aetna    27955.096079          205      Emergency     2022-10-07      Aspirin        Normal      Elderly
3   andrEw waTtS   28  Female         O+          Diabetes        2020-11-18       Kevin Wells  Hernandez Rogers and Vang,           Medicare    37909.782410          450       Elective     2020-12-18    Ibuprofen      Abnormal  Young Adult
4  adrIENNE bEll   43  Female        AB+            Cancer        2022-09-19    Kathleen Hanna                 White-White              Aetna    14238.317814          458         Urgent     2022-10-09   Penicillin      Abnormal        Adult

In [ ]:
df["age_group"].value_counts()

age_group
Elderly        16096
Young Adult    13519
Senior         12298
Adult          12167
Child            886
Name: count, dtype: int64

In [ ]:
df["admission_year"] = df["date_of_admission"].dt.year

df["admission_month"] = df["date_of_admission"].dt.month_name()

df["admission_day"] = df["date_of_admission"].dt.day_name()

df["admission_quarter"] = "Q" + df["date_of_admission"].dt.quarter.astype(str)

df.head()

            name  age  gender blood_type medical_condition date_of_admission            doctor                    hospital insurance_provider  billing_amount  room_number admission_type discharge_date   medication  test_results    age_group  admission_year admission_month admission_day admission_quarter
0  Bobby JacksOn   30    Male         B-            Cancer        2024-01-31     Matthew Smith             Sons and Miller         Blue Cross    18856.281306          328         Urgent     2024-02-02  Paracetamol        Normal  Young Adult            2024         January     Wednesday                Q1
1   LesLie TErRy   62    Male         A+           Obesity        2019-08-20   Samantha Davies                     Kim Inc           Medicare    33643.327287          265      Emergency     2019-08-26    Ibuprofen  Inconclusive       Senior            2019          August       Tuesday                Q3
2    DaNnY sMitH   76  Female         A-           Obesity        2022-09-22  Tiffany Mitchell                    Cook PLC              Aetna    27955.096079          205      Emergency     2022-10-07      Aspirin        Normal      Elderly            2022       September      Thursday                Q3
3   andrEw waTtS   28  Female         O+          Diabetes        2020-11-18       Kevin Wells  Hernandez Rogers and Vang,           Medicare    37909.782410          450       Elective     2020-12-18    Ibuprofen      Abnormal  Young Adult            2020        November     Wednesday                Q4
4  adrIENNE bEll   43  Female        AB+            Cancer        2022-09-19    Kathleen Hanna                 White-White              Aetna    14238.317814          458         Urgent     2022-10-09   Penicillin      Abnormal        Adult            2022       September        Monday                Q3

In [ ]:
df["date_of_admission"] = pd.to_datetime(df["date_of_admission"])

df["discharge_date"] = pd.to_datetime(df["discharge_date"])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54966 entries, 0 to 54965
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          54966 non-null  int64
 1   name                54966 non-null  object
 2   age                 54966 non-null  int64
 3   gender              54966 non-null  object
 4   blood_type          54966 non-null  object
 5   medical_condition   54966 non-null  object
 6   date_of_admission   54966 non-null  datetime64[ns]
 7   doctor              54966 non-null  object
 8   hospital            54966 non-null  object
 9   insurance_provider  54966 non-null  object
 10  billing_amount      54966 non-null  float64
 11  room_number         54966 non-null  int64
 12  admission_type      54966 non-null  object
 13  discharge_date      54966 non-null  datetime64[ns]
 14  medication          54966 non-null  object
 15  test_results        54966 non-null  object
 16  age_group           54966 non-null  category
 17  admission_year      54966 non-null  int32
 18  admission_month     54966 non-null  object
 19  admission_day       54966 non-null  object
 20  admission_quarter   54966 non-null  object
dtypes: category(1), datetime64[ns](2), float64(1), int32(1), int64(3), object(13)
memory usage: 8.2+ MB

In [ ]:
df["length_of_stay"] = (
    df["discharge_date"] -
    df["date_of_admission"]
).dt.days

In [ ]:
df["length_of_stay"].describe()

count    54966.000000
mean        15.499290
std          8.661471
min          1.000000
25%          8.000000
50%         15.000000
75%         23.000000
max         30.000000
Name: length_of_stay, dtype: float64

In [ ]:
df["billing_amount"].describe()

count    54966.000000
mean     25544.306284
std      14208.409711
min      -2008.492140
25%      13243.718641
50%      25542.749145
75%      37819.858159
max      52764.276736
Name: billing_amount, dtype: float64

In [ ]:
df[df["billing_amount"] < 0]

                           name  age  gender blood_type medical_condition date_of_admission               doctor                   hospital insurance_provider  billing_amount  room_number admission_type discharge_date   medication  test_results    age_group  admission_year admission_month admission_day admission_quarter
132             ashLEy ERIcKSoN   32  Female        AB-            Cancer        2019-11-05        Gerald Hooper  and Johnson Moore, Branch              Aetna     -502.507813          376         Urgent     2019-11-23   Penicillin        Normal  Young Adult            2019        November       Tuesday                Q4
799           CHRisTOPHer wEiss   49  Female        AB-            Asthma        2023-02-16       Kelly Thompson              Hunter-Hughes              Aetna    -1018.245371          204       Elective     2023-03-09   Penicillin  Inconclusive        Adult            2023        February      Thursday                Q1
1018              AsHley WaRnER   60    Male         A+      Hypertension        2021-12-21       Andrea Bentley      and Wagner, Lee Klein              Aetna     -306.364925          426       Elective     2022-01-11    Ibuprofen        Normal       Senior            2021        December       Tuesday                Q4
1421               JAY galloWaY   74  Female         O+            Asthma        2021-01-20        Debra Everett               Group Peters         Blue Cross     -109.097122          381      Emergency     2021-02-09    Ibuprofen      Abnormal      Elderly            2021         January     Wednesday                Q1
2103          josHUa wilLIamSon   72  Female         B-          Diabetes        2021-03-21          Wendy Ramos    and Huff Reeves, Dennis         Blue Cross     -576.727907          369         Urgent     2021-04-17      Aspirin      Abnormal      Elderly            2021           March        Sunday                Q1
...                         ...  ...     ...        ...               ...               ...                  ...                        ...                ...             ...          ...            ...            ...          ...           ...          ...             ...             ...           ...               ...
51994  mr. ChRIStOPhER aLvARaDO   74    Male        AB+           Obesity        2022-06-03  Mr. Dean Guzman DDS                Johnson Inc         Blue Cross    -1310.272895          257       Elective     2022-06-13  Paracetamol  Inconclusive      Elderly            2022            June        Friday                Q2
52376          gABrieLlE deCkER   66    Male        AB-         Arthritis        2022-11-07       William Krause                Diaz-Bishop              Cigna     -676.852502          354         Urgent     2022-11-30   Penicillin        Normal      Elderly            2022        November        Monday                Q4
52896             AsHley WaRnER   55    Male         A+      Hypertension        2021-12-21       Andrea Bentley      and Wagner, Lee Klein              Aetna     -306.364925          426       Elective     2022-01-11    Ibuprofen        Normal       Senior            2021        December       Tuesday                Q4
52923              dAnIel dRaKe   68  Female         B+      Hypertension        2020-04-24            Brett Ray                   Carr Ltd              Aetna     -591.917419          426       Elective     2020-04-26      Lipitor      Abnormal      Elderly            2020           April        Friday                Q2
53747         DR. micHaEl MckAy   64    Male         O+            Cancer        2019-05-31         Dawn Navarro  Mcconnell and Rios, Clark   UnitedHealthcare     -199.663795          122         Urgent     2019-06-12    Ibuprofen      Abnormal       Senior            2019             May        Friday                Q2

[106 rows x 20 columns]

In [ ]:
negative_count = (df["billing_amount"] < 0).sum()

print("Negative Billing Records:", negative_count)

Negative Billing Records: 106

In [ ]:
billing_median = df.loc[
    df["billing_amount"] >= 0,
    "billing_amount"
].median()

print("Median Billing Amount:", round(billing_median, 2))

Median Billing Amount: 25593.87

In [ ]:
df.loc[
    df["billing_amount"] < 0,
    "billing_amount"
] = billing_median

In [ ]:
print("Negative Billing Records:",
      (df["billing_amount"] < 0).sum())

Negative Billing Records: 0

In [ ]:
# Standardize Text Columns
text_columns = [
    "name",
    "doctor",
    "hospital"
]

for col in text_columns:
    df[col] = (
        df[col]
        .str.strip()
        .str.title()
    )

In [ ]:
df[["name", "doctor", "hospital"]].head()

            name            doctor                    hospital
0  Bobby Jackson     Matthew Smith             Sons And Miller
1   Leslie Terry   Samantha Davies                     Kim Inc
2    Danny Smith  Tiffany Mitchell                    Cook Plc
3   Andrew Watts       Kevin Wells  Hernandez Rogers And Vang,
4  Adrienne Bell    Kathleen Hanna                 White-White

In [ ]:
df.head()

   patient_id           name  age  gender blood_type medical_condition date_of_admission            doctor                    hospital insurance_provider  billing_amount  room_number admission_type discharge_date   medication  test_results    age_group  admission_year admission_month admission_day admission_quarter  length_of_stay
0           1  Bobby Jackson   30    Male         B-            Cancer        2024-01-31     Matthew Smith             Sons And Miller         Blue Cross    18856.281306          328         Urgent     2024-02-02  Paracetamol        Normal  Young Adult            2024         January     Wednesday                Q1               2
1           2   Leslie Terry   62    Male         A+           Obesity        2019-08-20   Samantha Davies                     Kim Inc           Medicare    33643.327287          265      Emergency     2019-08-26    Ibuprofen  Inconclusive       Senior            2019          August       Tuesday                Q3               6
2           3    Danny Smith   76  Female         A-           Obesity        2022-09-22  Tiffany Mitchell                    Cook Plc              Aetna    27955.096079          205      Emergency     2022-10-07      Aspirin        Normal      Elderly            2022       September      Thursday                Q3              15
3           4   Andrew Watts   28  Female         O+          Diabetes        2020-11-18       Kevin Wells  Hernandez Rogers And Vang,           Medicare    37909.782410          450       Elective     2020-12-18    Ibuprofen      Abnormal  Young Adult            2020        November     Wednesday                Q4              30
4           5  Adrienne Bell   43  Female        AB+            Cancer        2022-09-19    Kathleen Hanna                 White-White              Aetna    14238.317814          458         Urgent     2022-10-09   Penicillin      Abnormal        Adult            2022       September        Monday                Q3              20

In [ ]:
df.dtypes

patient_id                     int64
name                          object
age                            int64
gender                        object
blood_type                    object
medical_condition             object
date_of_admission     datetime64[ns]
doctor                        object
hospital                      object
insurance_provider            object
billing_amount               float64
room_number                    int64
admission_type                object
discharge_date        datetime64[ns]
medication                    object
test_results                  object
age_group                   category
admission_year                 int32
admission_month               object
admission_day                 object
admission_quarter             object
length_of_stay                 int64
dtype: object

In [ ]:
for col in df.columns:
    print(f"\n{col}")
    print(df[col].nunique())

patient_id
54966

name
40235

age
77

gender
2

blood_type
8

medical_condition
6

date_of_admission
1827

doctor
40341

hospital
39876

insurance_provider
5

billing_amount
49905

room_number
400

admission_type
3

discharge_date
1856

medication
5

test_results
3

age_group
5

admission_year
6

admission_month
12

admission_day
7

admission_quarter
4

length_of_stay
30

In [ ]:
categorical_columns = [
    "gender",
    "blood_type",
    "medical_condition",
    "admission_type",
    "medication",
    "insurance_provider",
    "test_results"
]

for col in categorical_columns:
    print("\n")
    print(col)
    print(df[col].unique())

gender
['Male' 'Female']


blood_type
['B-' 'A+' 'A-' 'O+' 'AB+' 'AB-' 'B+' 'O-']


medical_condition
['Cancer' 'Obesity' 'Diabetes' 'Asthma' 'Hypertension' 'Arthritis']


admission_type
['Urgent' 'Emergency' 'Elective']


medication
['Paracetamol' 'Ibuprofen' 'Aspirin' 'Penicillin' 'Lipitor']


insurance_provider
['Blue Cross' 'Medicare' 'Aetna' 'UnitedHealthcare' 'Cigna']


test_results
['Normal' 'Inconclusive' 'Abnormal']

In [ ]:
print("Dataset Shape:", df.shape)
print("Duplicate Records:", df.duplicated().sum())
print("Negative Billing:", (df["billing_amount"] < 0).sum())
print("Missing Values:\n", df.isnull().sum())

Dataset Shape: (54966, 22)
Duplicate Records: 0
Negative Billing: 0
Missing Values:
 patient_id            0
name                  0
age                   0
gender                0
blood_type            0
medical_condition     0
date_of_admission     0
doctor                0
hospital              0
insurance_provider    0
billing_amount        0
room_number           0
admission_type        0
discharge_date        0
medication            0
test_results          0
age_group             0
admission_year        0
admission_month       0
admission_day         0
admission_quarter     0
length_of_stay        0
dtype: int64

In [ ]:
df.to_csv("healthcare_cleaned.csv", index=False)